### ISSUE TITLE
Pact Kotlin dependency causing failures with continuous testing

### ISSUE THREAD

**Issue by holly-cummins** [holly-cummins/house-of-microservices-quarkus-contract-testing-sample#8]
I think this is a problem that would be fixed by a Pact extension. 

```
2022-08-31 14:12:28,815 ERROR [io.qua.test] (Test runner thread) Test HouseContractTest#pactVerificationTestTemplate(PactVerificationContext) failed 
: java.lang.AssertionError: Can't find built-in class kotlin.Any
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getBuiltInClassByFqName(KotlinBuiltIns.java:217)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JavaToKotlinClassMapper.mapJavaToKotlin(JavaToKotlinClassMapper.kt:41)
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JavaToKotlinClassMapper.mapJavaToKotlin$default(JavaToKotlinClassMapper.kt:37)
        at kotlin.reflect.jvm.internal.impl.load.java.lazy.types.JavaTypeResolver.mapKotlinClass(JavaTypeResolver.kt:168)
        at kotlin.reflect.jvm.internal.impl.load.java.lazy.types.JavaTypeResolver.computeTypeConstructor(JavaTypeResolver.kt:142)
        at kotlin.reflect.jvm.internal.impl.load.java.lazy.types.JavaTypeResolver.computeSimpleJavaClassifierType(JavaTypeResolver.kt:124)
        at kotlin.reflect.jvm.internal.impl.load.java.lazy.types.JavaTypeResolver.transformJavaClassifierType(JavaTypeResolver.kt:100)
        at kotlin.reflect.jvm.internal.impl.load.java.lazy.types.JavaTypeResolver.transformJavaType(JavaTypeResolver.kt:54)
        at kotlin.reflect.jvm.internal.impl.load.java.lazy.descriptors.LazyJavaClassDescriptor$LazyJavaClassTypeConstructor.computeSupertypes(LazyJavaClassDescriptor.kt:220)
```

**Comment by holly-cummins** [comment]
Adding the dependency exposes a second problem, where the pact files cannot be found.
